// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package drophere_go

import (
	"time"
)

type Link struct {
	ID          int        `json:"id"`
	Title       string     `json:"title"`
	IsProtected bool       `json:"isProtected"`
	Slug        *string    `json:"slug"`
	Description *string    `json:"description"`
	Deadline    *time.Time `json:"deadline"`
}

type Message struct {
	Message string `json:"message"`
}

type Token struct {
	LoginToken string `json:"loginToken"`
}

type User struct {
	ID            int     `json:"id"`
	Email         string  `json:"email"`
	Name          string  `json:"name"`
	Dropboxauth   *bool   `json:"dropboxauth"`
	Dropboxemail  *string `json:"dropboxemail"`
	Dropboxavatar *string `json:"dropboxavatar"`
}
